# Amostragens

In [3]:
import numpy as np
import pandas as pd

In [4]:
enem_sp = pd.read_csv('enem_2019_tratado.csv', sep=',', encoding='iso-8859-1')

In [5]:
enem_sp.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,NaN,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,15567761.0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,Não
2,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,35904958.0,...,393.2,Espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
3,"1,90E+11",Embu-Guaçu,17,F,1,parda,1,2,pública,NaN,...,419.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
4,"1,90E+11",Guarulhos,23,F,1,branca,1,1,não_respondeu,NaN,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim

In [6]:
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas'] # localizar na coluna

In [7]:
enem_campinas.head(10)

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
15,"1,90E+11",Campinas,17,F,1,branca,1,1,não_respondeu,NaN,...,496.5,Inglês,1.0,160.0,120.0,140.0,140.0,120.0,680.0,Sim
31,"1,90E+11",Campinas,19,F,1,parda,1,1,não_respondeu,NaN,...,73.1,Inglês,1.0,140.0,120.0,160.0,140.0,160.0,720.0,Sim
51,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
116,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,26078562.0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
169,"1,90E+11",Campinas,17,M,1,branca,1,2,privada,NaN,...,624.4,Inglês,1.0,140.0,120.0,140.0,160.0,160.0,720.0,Sim
186,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,628.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
236,"1,90E+11",Campinas,17,F,1,preta,1,2,privada,35112859.0,...,499.8,Inglês,1.0,160.0,120.0,120.0,160.0,200.0,760.0,Sim
325,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35907376.0,...,509.3,Inglês,1.0,80.0,120.0,100.0,100.0,80.0,480.0,Sim
401,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
469,"1,90E+11",Campinas,18,M,1,nao_declarado,1,1,não_respondeu,NaN,...,669.4,Inglês,1.0,140.0,180.0,120.0,160.0,120.0,720.0,Sim

# Amostragem Aleatória Simples
Seleção por sorteio, sem filtros.

In [8]:
np.random.seed(1) # gera valor aleatório e sempre que rodar vai dar o mesmo número

- np.random.seed é usado para inicializar o gerador de números aleatórios do NumPy com uma semente específica.
- Serve para reproduzir resultados aleatórios em diferentes execuções do código.
- A semente deve ser definida antes de qualquer chamada a funções que geram números aleatórios.
- Se definida corretamente, produzirá a mesma sequência de números pseudoaleatórios em diferentes execuções.
- Se definida após a geração de números aleatórios, não terá efeito retroativo na sequência já gerada.
- Se, mesmo após definir a semente, os resultados continuarem diferentes, revise o código para garantir que todas as fontes de aleatoriedade sejam tratadas adequadamente.

In [9]:
# pega uma fração aleatória de enem campinas (amostragem aleatória) e pega 20% dos dados
amos_simples = enem_campinas.sample(frac=0.20) # porcentagem

In [10]:
amos_simples

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
327999,"1,90E+11",Campinas,20,M,1,preta,1,1,não_respondeu,NaN,...,459.6,Inglês,1.0,180.0,200.0,180.0,200.0,200.0,960.0,Sim
235222,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018296.0,...,48.8,Inglês,1.0,160.0,180.0,160.0,140.0,140.0,780.0,Sim
134221,"1,90E+11",Campinas,18,F,1,parda,1,2,pública,NaN,...,429.9,Inglês,1.0,100.0,120.0,100.0,80.0,100.0,500.0,Sim
358407,"1,90E+11",Campinas,25,M,0,parda,1,1,não_respondeu,NaN,...,687.4,Espanhol,1.0,140.0,120.0,120.0,140.0,140.0,660.0,Não
173364,"1,90E+11",Campinas,18,M,1,parda,1,1,não_respondeu,NaN,...,617.9,Inglês,1.0,140.0,120.0,140.0,140.0,80.0,620.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452747,"1,90E+11",Campinas,45,F,1,branca,1,1,não_respondeu,NaN,...,373.5,Espanhol,1.0,80.0,80.0,80.0,80.0,80.0,400.0,Sim
362918,"1,90E+11",Campinas,19,M,1,preta,1,1,não_respondeu,NaN,...,450.7,Inglês,1.0,120.0,40.0,40.0,120.0,0.0,320.0,Sim
221397,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,524.8,Espanhol,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
76628,"1,90E+11",Campinas,17,M,0,branca,1,2,pública,35018797.0,...,649.7,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
126402,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35039901.0,...,376.6,Espanhol,1.0,120.0,160.0,140.0,120.0,140.0,680.0,Sim

In [11]:
# seleciona aleatoriamente em quantidade numérica 
#amos_simples2 - enem_campinas.sample(30) # 3000 registros sorteados

In [12]:
amos_simples

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
327999,"1,90E+11",Campinas,20,M,1,preta,1,1,não_respondeu,NaN,...,459.6,Inglês,1.0,180.0,200.0,180.0,200.0,200.0,960.0,Sim
235222,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018296.0,...,48.8,Inglês,1.0,160.0,180.0,160.0,140.0,140.0,780.0,Sim
134221,"1,90E+11",Campinas,18,F,1,parda,1,2,pública,NaN,...,429.9,Inglês,1.0,100.0,120.0,100.0,80.0,100.0,500.0,Sim
358407,"1,90E+11",Campinas,25,M,0,parda,1,1,não_respondeu,NaN,...,687.4,Espanhol,1.0,140.0,120.0,120.0,140.0,140.0,660.0,Não
173364,"1,90E+11",Campinas,18,M,1,parda,1,1,não_respondeu,NaN,...,617.9,Inglês,1.0,140.0,120.0,140.0,140.0,80.0,620.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452747,"1,90E+11",Campinas,45,F,1,branca,1,1,não_respondeu,NaN,...,373.5,Espanhol,1.0,80.0,80.0,80.0,80.0,80.0,400.0,Sim
362918,"1,90E+11",Campinas,19,M,1,preta,1,1,não_respondeu,NaN,...,450.7,Inglês,1.0,120.0,40.0,40.0,120.0,0.0,320.0,Sim
221397,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,524.8,Espanhol,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
76628,"1,90E+11",Campinas,17,M,0,branca,1,2,pública,35018797.0,...,649.7,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
126402,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35039901.0,...,376.6,Espanhol,1.0,120.0,160.0,140.0,120.0,140.0,680.0,Sim

outra maneira...
cria amostra c valores diferentes e separa qual a proporção de cada uma delas, no final relaciona os dados de acordo com os novos dados/números

In [13]:
np.random.seed(2) # outra semestre p outro número aleatório

In [14]:
# faz a amostra com o tamanho tal com números 0 e 1, com 80% para 0 e 20% para 1
amostra = np.random.choice(a=[0,1], size=13198, replace=True, p=[0.8,0.2])

In [15]:
len(amostra[amostra == 0])

10566

In [16]:
len(amostra[amostra == 1])

2632

In [17]:
amos_simples = enem_campinas.loc[amostra == 1]

In [18]:
amos_simples

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
949,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35924573.0,...,601.4,Inglês,1.0,160.0,120.0,120.0,140.0,120.0,660.0,Sim
1058,"1,90E+11",Campinas,19,M,1,parda,1,1,não_respondeu,NaN,...,474.6,Inglês,1.0,120.0,120.0,120.0,160.0,100.0,620.0,Sim
1980,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35018302.0,...,479.9,Inglês,1.0,120.0,120.0,120.0,140.0,120.0,620.0,Não
2053,"1,90E+11",Campinas,18,F,1,parda,1,1,não_respondeu,NaN,...,424.2,Inglês,1.0,100.0,40.0,20.0,80.0,0.0,240.0,Sim
2328,"1,90E+11",Campinas,20,F,1,parda,2,1,não_respondeu,NaN,...,552.5,Espanhol,1.0,120.0,120.0,100.0,100.0,80.0,520.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498946,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35018797.0,...,484.1,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
499198,"1,90E+11",Campinas,18,M,1,preta,1,2,pública,35018363.0,...,666.4,Inglês,1.0,120.0,120.0,120.0,100.0,80.0,540.0,Sim
499258,"1,90E+11",Campinas,21,F,1,preta,1,1,não_respondeu,NaN,...,503.6,Inglês,1.0,120.0,120.0,120.0,140.0,120.0,620.0,Sim
499691,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,35018089.0,...,770.3,Inglês,1.0,120.0,120.0,120.0,160.0,80.0,600.0,Sim
499883,"1,90E+11",Campinas,20,F,1,branca,1,1,não_respondeu,NaN,...,701.1,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim

In [19]:
np.random.seed(40)

- IMPORTANTE

Para obter sempre os mesmo elementos da amostra, tem que rodar a linha de código relacionada a semente utilizada nessa amostra

```
np.random.seed(1)
```

# Amostragem Sistemática
Membros da população ordenados numericamente e selecionados de acordo com uma sequência numérica.

In [20]:
enem_campinas.shape

(13198, 28)

In [21]:
np.random.seed(2)
inicio = np.random.choice(10,1) # (limite do número, quantidade de números) seleciona número inicial p pegar elementos

In [22]:
inicio

array([8])

In [23]:
amostra2 = np.arange(inicio,13198,100) # (valor numérico inicial, valor total de linhas, sequência de x números em x números)
amostra2

array([    8,   108,   208,   308,   408,   508,   608,   708,   808,
         908,  1008,  1108,  1208,  1308,  1408,  1508,  1608,  1708,
        1808,  1908,  2008,  2108,  2208,  2308,  2408,  2508,  2608,
        2708,  2808,  2908,  3008,  3108,  3208,  3308,  3408,  3508,
        3608,  3708,  3808,  3908,  4008,  4108,  4208,  4308,  4408,
        4508,  4608,  4708,  4808,  4908,  5008,  5108,  5208,  5308,
        5408,  5508,  5608,  5708,  5808,  5908,  6008,  6108,  6208,
        6308,  6408,  6508,  6608,  6708,  6808,  6908,  7008,  7108,
        7208,  7308,  7408,  7508,  7608,  7708,  7808,  7908,  8008,
        8108,  8208,  8308,  8408,  8508,  8608,  8708,  8808,  8908,
        9008,  9108,  9208,  9308,  9408,  9508,  9608,  9708,  9808,
        9908, 10008, 10108, 10208, 10308, 10408, 10508, 10608, 10708,
       10808, 10908, 11008, 11108, 11208, 11308, 11408, 11508, 11608,
       11708, 11808, 11908, 12008, 12108, 12208, 12308, 12408, 12508,
       12608, 12708, 12808, 12908, 13008, 13108])

In [24]:
# daqui para cima tinhamos somente os números...

# queremos isso tabelado 

# "pegue na tabela enem_campinas os números da amostra2"
# iloc busca pelo índice de amostra2 na tabela
# ,: para todas as colunas referentes aos registros/índices
amos_sistematica = enem_campinas.iloc[amostra2,:] #

In [25]:
amos_sistematica

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
401,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
5079,"1,90E+11",Campinas,18,F,1,branca,1,2,pública,35018855.0,...,419.9,Inglês,1.0,140.0,120.0,120.0,120.0,140.0,640.0,Sim
9218,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,617.1,Inglês,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
13685,"1,90E+11",Campinas,20,M,1,parda,1,1,não_respondeu,NaN,...,576.4,Inglês,1.0,160.0,200.0,180.0,200.0,180.0,920.0,Sim
18239,"1,90E+11",Campinas,20,M,1,branca,1,1,não_respondeu,NaN,...,796.2,Inglês,1.0,160.0,200.0,200.0,200.0,200.0,960.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481894,"1,90E+11",Campinas,34,M,1,parda,1,1,não_respondeu,NaN,...,932.1,Inglês,1.0,140.0,120.0,160.0,160.0,160.0,740.0,Sim
485805,"1,90E+11",Campinas,16,F,1,branca,1,2,pública,35039901.0,...,441.6,Inglês,1.0,120.0,120.0,100.0,120.0,0.0,460.0,Sim
488958,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,492.9,Inglês,1.0,160.0,120.0,140.0,120.0,140.0,680.0,Sim
492626,"1,90E+11",Campinas,21,M,1,branca,1,1,não_respondeu,NaN,...,51.1,Inglês,1.0,120.0,120.0,120.0,100.0,0.0,460.0,Sim
496410,"1,90E+11",Campinas,19,M,1,preta,1,1,não_respondeu,NaN,...,404.4,Inglês,1.0,100.0,80.0,80.0,80.0,40.0,380.0,Sim

Outra Maneira

In [26]:
np.random.seed(3)

In [27]:
inicio = np.random.choice(10,1)
passo = np.random.randint(100,150,1) # escolhe um número entre 100 e 150, o passo representa o "100" anterior da outr amaneira de fazer amos sistem

In [28]:
inicio

array([8])

In [29]:
passo

array([103])

In [30]:
amostra2 = np.arange(inicio,13198,passo)
amostra2

array([    8,   111,   214,   317,   420,   523,   626,   729,   832,
         935,  1038,  1141,  1244,  1347,  1450,  1553,  1656,  1759,
        1862,  1965,  2068,  2171,  2274,  2377,  2480,  2583,  2686,
        2789,  2892,  2995,  3098,  3201,  3304,  3407,  3510,  3613,
        3716,  3819,  3922,  4025,  4128,  4231,  4334,  4437,  4540,
        4643,  4746,  4849,  4952,  5055,  5158,  5261,  5364,  5467,
        5570,  5673,  5776,  5879,  5982,  6085,  6188,  6291,  6394,
        6497,  6600,  6703,  6806,  6909,  7012,  7115,  7218,  7321,
        7424,  7527,  7630,  7733,  7836,  7939,  8042,  8145,  8248,
        8351,  8454,  8557,  8660,  8763,  8866,  8969,  9072,  9175,
        9278,  9381,  9484,  9587,  9690,  9793,  9896,  9999, 10102,
       10205, 10308, 10411, 10514, 10617, 10720, 10823, 10926, 11029,
       11132, 11235, 11338, 11441, 11544, 11647, 11750, 11853, 11956,
       12059, 12162, 12265, 12368, 12471, 12574, 12677, 12780, 12883,
       12986, 13089, 13192])

In [31]:
amostra2_camp = enem_campinas.iloc[amostra2,:]

In [32]:
amostra2_camp

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
401,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
5229,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,606.2,Inglês,1.0,140.0,120.0,160.0,160.0,80.0,660.0,Sim
9455,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,620.6,Inglês,1.0,140.0,140.0,140.0,120.0,120.0,660.0,Não
13926,"1,90E+11",Campinas,21,M,1,preta,1,1,não_respondeu,NaN,...,545.6,Inglês,1.0,160.0,160.0,120.0,120.0,140.0,700.0,Não
18554,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,NaN,...,701.5,Inglês,1.0,160.0,200.0,180.0,160.0,200.0,900.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484690,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35018788.0,...,54.1,Inglês,1.0,100.0,100.0,100.0,120.0,80.0,500.0,Sim
488340,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,542.3,Espanhol,1.0,120.0,120.0,140.0,120.0,80.0,580.0,Sim
491708,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,423.4,Inglês,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
495779,"1,90E+11",Campinas,20,M,1,preta,1,1,não_respondeu,NaN,...,465.8,Inglês,1.0,120.0,40.0,40.0,120.0,0.0,320.0,Sim
499691,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,35018089.0,...,770.3,Inglês,1.0,120.0,120.0,120.0,160.0,80.0,600.0,Sim

# Amostragem Estratificada
Divisão em grupos da população e seleção aleatória de uma amostra de cada grupo.

In [33]:
enem_campinas['RACA'].value_counts() # analise estratificada para raça

RACA
branca           7507
parda            3652
preta            1510
amarela           279
nao_declarado     205
indigena           45
Name: count, dtype: int64

In [34]:
branca = enem_campinas.loc[enem_campinas.RACA == 'branca'].sample(frac=0.15)
branca.shape

(1126, 28)

In [35]:
parda = enem_campinas.loc[enem_campinas.RACA == 'parda'].sample(frac=0.15)
parda.shape

(548, 28)

In [36]:
preta = enem_campinas.loc[enem_campinas.RACA == 'preta'].sample(frac=0.15)
preta.shape

(226, 28)

In [37]:
amarela = enem_campinas.loc[enem_campinas.RACA == 'amarela'].sample(frac=0.15)
amarela.shape

(42, 28)

In [38]:
nd = enem_campinas.loc[enem_campinas.RACA == 'nao_declarado'].sample(frac=0.15)
nd.shape

(31, 28)

In [39]:
indigena = enem_campinas.loc[enem_campinas.RACA == 'indígena'].sample(frac=0.15)
indigena.shape

(0, 28)

In [40]:
amos_estra = pd.concat([branca, parda, preta, amarela, nd, indigena]) # concatenando as variáveis

In [41]:
amos_estra

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
25195,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35112859.0,...,496.3,Inglês,1.0,120.0,100.0,100.0,100.0,100.0,520.0,Sim
466174,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35045937.0,...,668.9,Inglês,1.0,140.0,140.0,120.0,180.0,160.0,740.0,Não
22297,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018235.0,...,499.2,Inglês,1.0,140.0,120.0,140.0,120.0,60.0,580.0,Sim
414163,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,46.7,Inglês,1.0,120.0,120.0,80.0,120.0,0.0,440.0,Sim
235084,"1,90E+11",Campinas,27,M,1,branca,1,1,não_respondeu,NaN,...,684.5,Inglês,1.0,140.0,140.0,120.0,120.0,80.0,600.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363687,"1,90E+11",Campinas,19,F,1,nao_declarado,1,1,não_respondeu,NaN,...,525.1,Espanhol,1.0,140.0,120.0,120.0,140.0,180.0,700.0,Sim
444775,"1,90E+11",Campinas,17,M,1,nao_declarado,1,2,pública,35917758.0,...,46.7,Inglês,1.0,120.0,120.0,120.0,140.0,100.0,600.0,Sim
253783,"1,90E+11",Campinas,17,F,1,nao_declarado,1,2,pública,35045585.0,...,485.2,Inglês,1.0,120.0,40.0,40.0,120.0,40.0,360.0,Sim
391553,"1,90E+11",Campinas,17,M,1,nao_declarado,1,2,privada,35112773.0,...,853.5,Inglês,1.0,160.0,180.0,180.0,160.0,160.0,840.0,Sim
128988,"1,90E+11",Campinas,45,F,1,nao_declarado,1,1,não_respondeu,NaN,...,488.2,Espanhol,1.0,120.0,120.0,100.0,100.0,0.0,440.0,Não

**Grandes quantidades de grupos**
Para grandes grupos, fica inviável na maneira acima. Fazemos o seguinte:

In [42]:
from sklearn.model_selection import train_test_split 
# importando "treino teste", muito utilizado em machine learning

In [ ]:
X_treino, X_teste, y_treino, amos_estra = train_test_split(enem_campinas.drop('RACA',axis=1),enem_campinas['RACA'],
                                                    stratify=enem_campinas['RACA'], test_size=0.20) # axis=1 (coluna), extrair amostra c 20% do tamanho

In [ ]:
amos_estra.shape

(2640,)

In [ ]:
amos_estra.value_counts()

RACA
branca           1502
parda             730
preta             302
amarela            56
nao_declarado      41
indigena            9
Name: count, dtype: int64

In [ ]:
amos_estra = amos_estra.index # colocando index para poder concatenar

In [ ]:
amos_estra

Index([191633, 260946, 225431, 371529,  98563, 291455, 225412, 247934, 437437,
       118988,
       ...
        77834, 124362,  49996,  52531, 202712, 419268, 471381,  64658, 325952,
       272768],
      dtype='int64', length=2640)

In [ ]:
amos_estra_camp = enem_campinas.loc[amos_estra,:]

In [ ]:
amos_estra_camp

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
191633,"1,90E+11",Campinas,19,F,1,preta,1,1,não_respondeu,NaN,...,594.8,Espanhol,1.0,120.0,120.0,100.0,100.0,80.0,520.0,Sim
260946,"1,90E+11",Campinas,23,M,1,indigena,1,1,não_respondeu,NaN,...,529.1,Espanhol,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Não
225431,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35445897.0,...,466.4,Espanhol,1.0,120.0,40.0,40.0,100.0,0.0,300.0,Sim
371529,"1,90E+11",Campinas,17,M,1,branca,1,2,privada,35144757.0,...,66.8,Inglês,1.0,120.0,120.0,120.0,120.0,60.0,540.0,Sim
98563,"1,90E+11",Campinas,17,M,0,parda,1,2,privada,NaN,...,804.7,Inglês,1.0,160.0,180.0,160.0,200.0,200.0,900.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419268,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,772.5,Inglês,1.0,160.0,160.0,180.0,140.0,160.0,800.0,Sim
471381,"1,90E+11",Campinas,22,F,1,parda,1,1,não_respondeu,NaN,...,768.8,Inglês,1.0,140.0,160.0,200.0,180.0,200.0,880.0,Sim
64658,"1,90E+11",Campinas,21,F,1,branca,1,1,não_respondeu,NaN,...,64.3,Inglês,1.0,160.0,180.0,180.0,160.0,180.0,860.0,Sim
325952,"1,90E+11",Campinas,19,F,1,parda,1,1,não_respondeu,NaN,...,439.5,Inglês,1.0,120.0,120.0,100.0,120.0,80.0,540.0,Sim
272768,"1,90E+11",Campinas,21,F,1,branca,1,1,não_respondeu,NaN,...,729.8,Inglês,1.0,180.0,120.0,160.0,180.0,160.0,800.0,Sim

# Amostragem Conglomerado (Agrupamento)
Divisão da população em grupos, seleção de grupos aleatórios e análise de todos os seus elementos.

In [ ]:
escolas_publicas = enem_campinas.loc[enem_campinas.ESCOLA == 'pública']

In [ ]:
escolas_publicas

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
51,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
116,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,26078562.0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
325,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35907376.0,...,509.3,Inglês,1.0,80.0,120.0,100.0,100.0,80.0,480.0,Sim
949,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35924573.0,...,601.4,Inglês,1.0,160.0,120.0,120.0,140.0,120.0,660.0,Sim
1004,"1,90E+11",Campinas,24,F,1,branca,1,2,pública,35980158.0,...,359.8,Espanhol,1.0,120.0,40.0,100.0,100.0,60.0,420.0,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499530,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35042651.0,...,491.6,Inglês,1.0,140.0,120.0,120.0,160.0,120.0,660.0,Sim
499640,"1,90E+11",Campinas,22,M,1,preta,1,2,pública,35018533.0,...,365.4,Espanhol,1.0,80.0,60.0,60.0,80.0,0.0,280.0,Sim
499691,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,35018089.0,...,770.3,Inglês,1.0,120.0,120.0,120.0,160.0,80.0,600.0,Sim
499749,"1,90E+11",Campinas,17,M,1,branca,1,2,pública,35040400.0,...,405.1,Espanhol,1.0,120.0,80.0,80.0,100.0,60.0,440.0,Sim
499862,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018879.0,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim

In [ ]:
amostras = escolas_publicas['CO_ESCOLA'].value_counts() # grupo de escolas públicas, escolas diferentes com diferentes códigos
amostras

CO_ESCOLA
35045937.0    152
35018363.0    134
35018797.0    124
35018879.0    110
35018326.0    109
             ...
35462822.0      1
35058836.0      1
35112926.0      1
35017255.0      1
35047053.0      1
Name: count, Length: 186, dtype: int64

In [ ]:
# agora, temos que selecionar essas diferentes escolas que usaremos, os grupos q foram escolhidos para o conglomerado
# primeiro, temos que separar por índicees
amostras.index

Index([35045937.0, 35018363.0, 35018797.0, 35018879.0, 35018326.0, 35047200.0,
       35901097.0, 35045949.0, 35018235.0, 35018302.0,
       ...
       35018181.0, 35445757.0, 35045724.0, 35432842.0, 35039834.0, 35462822.0,
       35058836.0, 35112926.0, 35017255.0, 35047053.0],
      dtype='float64', name='CO_ESCOLA', length=186)

In [ ]:
amos_conglomerado.shape

In [ ]:
amostragem = np.random.choice(a=[0,1], size=186, replace=True, p=[0.85, 0.15]) # 0 e 1 para escolhidas e não escolhidas, tamanho do vetor de amostras, replate=True significa "com reposição", probabilidades para 0 e 1

In [ ]:
amostragem

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
# as escolas "diferentes" selecionadas foram as que tem "1", agora tem que relacinoar esse número 1 com essa escola diferente escolhida (o grupo escolhido!)
amos_conglomerado = amostras.loc[amostragem == 1] # localizar somente as que tem o número 1, pois queremos 15% somente. poderia ser 0 se quisesse a outra porcentagem

In [ ]:
amos_conglomerado

CO_ESCOLA
35018797.0    124
35018351.0     59
35018314.0     58
35018284.0     43
35905471.0     35
35018120.0     32
35018168.0     30
35018533.0     27
35018296.0     25
35018272.0     24
35467765.0     23
35018880.0     20
35018594.0     20
35914897.0     19
35125568.0     19
35018818.0     13
35901131.0     13
35045697.0     11
35042626.0      9
35065535.0      9
35018156.0      7
35004252.0      6
35018119.0      4
35112641.0      3
35582803.0      3
35907388.0      3
35179905.0      3
35123754.0      2
35112586.0      2
35112537.0      2
35337833.0      1
35917552.0      1
35800387.0      1
35047053.0      1
Name: count, dtype: int64

In [ ]:
amos_conglomerado.shape

(34,)

In [ ]:
amostragem

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
amos_conglomerado.index

Index([35018797.0, 35018351.0, 35018314.0, 35018284.0, 35905471.0, 35018120.0,
       35018168.0, 35018533.0, 35018296.0, 35018272.0, 35467765.0, 35018880.0,
       35018594.0, 35914897.0, 35125568.0, 35018818.0, 35901131.0, 35045697.0,
       35042626.0, 35065535.0, 35018156.0, 35004252.0, 35018119.0, 35112641.0,
       35582803.0, 35907388.0, 35179905.0, 35123754.0, 35112586.0, 35112537.0,
       35337833.0, 35917552.0, 35800387.0, 35047053.0],
      dtype='float64', name='CO_ESCOLA')

In [ ]:
amos_conglomerado = escolas_publicas.loc[escolas_publicas['CO_ESCOLA'].isin([35018797.0, 35018351.0, 35018314.0, 35018284.0, 35905471.0, 35018120.0,
       35018168.0, 35018533.0, 35018296.0, 35018272.0, 35467765.0, 35018880.0,
       35018594.0, 35914897.0, 35125568.0, 35018818.0, 35901131.0, 35045697.0,
       35042626.0, 35065535.0, 35018156.0, 35004252.0, 35018119.0, 35112641.0,
       35582803.0, 35907388.0, 35179905.0, 35123754.0, 35112586.0, 35112537.0,
       35337833.0, 35917552.0, 35800387.0, 35047053.0])] # colocando os números que tem "1" em ordem 
# isin busca os códigos, pois não são índices!

In [ ]:
amos_conglomerado

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
2066,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35905471.0,...,598.8,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim
6290,"1,90E+11",Campinas,17,M,1,preta,1,2,pública,35018351.0,...,471.4,Espanhol,1.0,140.0,120.0,160.0,160.0,160.0,740.0,Sim
6748,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35914897.0,...,547.5,Inglês,1.0,120.0,120.0,120.0,160.0,120.0,640.0,Sim
9673,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35018797.0,...,523.8,Inglês,1.0,120.0,120.0,100.0,120.0,80.0,540.0,Sim
10022,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35905471.0,...,455.9,Inglês,1.0,120.0,120.0,100.0,120.0,0.0,460.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498773,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018284.0,...,546.4,Inglês,1.0,100.0,120.0,100.0,120.0,40.0,480.0,Sim
498931,"1,90E+11",Campinas,21,F,1,branca,1,2,pública,35018533.0,...,426.9,Inglês,1.0,80.0,120.0,80.0,80.0,20.0,380.0,Sim
498946,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35018797.0,...,484.1,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
499026,"1,90E+11",Campinas,17,M,2,parda,1,2,pública,35905471.0,...,388.9,Inglês,1.0,100.0,60.0,60.0,100.0,0.0,320.0,Sim
499640,"1,90E+11",Campinas,22,M,1,preta,1,2,pública,35018533.0,...,365.4,Espanhol,1.0,80.0,60.0,60.0,80.0,0.0,280.0,Sim